# Generated by Django 6.0.6 on 2026-08-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewRoom",
            fields=[
                (
                    "room_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewRoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255, unique=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="submissions.interviewroom",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["room", "last_seen"],
                        name="submissions_room_id_85c27e_idx",
                    )
                ],
            },
        ),
    ]
