# Generated by Django 6.0.6 on 2026-08-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewroomparticipant",
            name="session_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="interviewroomparticipant",
            index=models.Index(
                fields=["room", "session_id"], name="submissions_room_id_1d374c_idx"
            ),
        ),
    ]
